### ISSUE TITLE
Error changing user status from admin.

### ISSUE THREAD

**Issue by GNURub** [mercurjs/mercur-api-starter#30]
```
error:   property status should not exist
Error: property status should not exist
    at /marketplace/api/node_modules/@medusajs/medusa/dist/utils/validator.js:153:31
    at step (/marketplace/api/node_modules/@medusajs/medusa/dist/utils/validator.js:44:23)
    at Object.next (/marketplace/api/node_modules/@medusajs/medusa/dist/utils/validator.js:25:53)
    at fulfilled (/marketplace/api/node_modules/@medusajs/medusa/dist/utils/validator.js:16:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'invalid_data',
  code: undefined,
  date: 2024-08-23T11:08:55.585Z
}
```

**Comment by KieranTravers** [comment]
I cant remember exactly but I had a very similar or the same issue, it stemmed from the users table in my database... Worth a check!

**Comment by GNURub** [comment]
The project is newly installed. I have not made any changes to the entire project. There is only the seed.json user and the vendor user for testing, which is the one that cannot be validated.
